default_model_faiss: "gpt-4o-mini"

llm:

  gpt-4o:
    model_name: "gpt-4o"
    temperature: 0.5
    embeddings: "OpenAIEmbeddings"
    faisspath: openai_faiss_index

  gpt-4o-mini:
    model_name: "gpt-4o-mini"
    temperature: 0.5
    embeddings: "OpenAIEmbeddings"
    faisspath: openai_faiss_index

  llama3:
    model_name: "llama3"
    temperature: 0.5
    embeddings: "HuggingFaceEmbeddings"
    faisspath: llama_faiss_index
    