llm:

  gpt-4o-mini:
    model_name: "gpt-4o-mini"
    temperature: 0.5
    vectorisation_path: vectorisations/openai_faiss_index

  gpt-4o:
    model_name: "gpt-4o"
    temperature: 0.5
    vectorisation_path: vectorisations/openai_chroma_db

  llama3:
    model_name: "llama3"
    temperature: 0.5
    vectorisation_path: vectorisations/llama_faiss_index
    