# NOM DU SITE WEB
NAME: "{NAME}"

# URL DE BASE DU SITE WEB
BASE_URL: "{BASE_URL}"

# URL DU PLAN DU SITE WEB
SITEMAP_URL: "{SITEMAP_URL}"

# PRÉFIXES DES URL À EXCLURE
EXCLUDE_URL_KEYWORDS:
  - "{EXCLUDE_URL_KEYWORDS}"

# DATE DE MODIFICATION DU SCRAPING
# Cette date est mise à jour à chaque fois que le scraping est effectué
LAST_MODIFIED_DATE: null
